### ISSUE TITLE
Script# TestClass Template does not compile

### ISSUE THREAD

**Issue by crystalbyte** [nikhilk/scriptsharp#105]
When adding a TestClass to an existing Script# unit test project, the following code is generated.

http://img821.imageshack.us/img821/3572/testclasserror.png

Items marked in "Red" are not known by the compiler.
Since I haven't been able to find any documentation on unit testing its hard to tell whether this is an Script# issue or if I'm just missing some VS components and/pr includes.

Still, many thanks Nikhilk for this amazing project ;)

**Comment by nikhilk** [comment]
A script# test class gets added to a script# project, and not to a unit test project.

The script# test class should be placed within a Tests subfolder in your script# project and gets compiled along with the rest of your script to produce a Foo.test.js (alongside Foo.debug.js and Foo.js). This is so that:
a) You can write your test javascript in c#.
b) You can access internal classes etc. in your test project, and everything gets minimized as a whole (otherwise you would have to guess the minimized names to write script against them).

Things like the TestClass base class and TestEngine are in the script# mscorlib, and hence you'll see errors if you add this to a unit test project.

All of the script# test class and tests compile to script and use QUnit at runtime.

Your unit test project (created using the script# unit test project in the Add Project folder) on the other hand does two things:
1. Provide a test runner - starts a web server, deploys files, and launches the browser to load pages.
2. Integrate with visual studio's test project UI - eg. test list view, test run results etc.

I really need to doc this ... did you see the samples which include test classes and a unit test project?

**Comment by crystalbyte** [comment]
It all makes sense at last ;)
I looked at the samples, but I haven't found the associated C# source for the unit tests, so I gathered they have to be written in javascript using QUnit, which I did at last.
It was not that big an issue, unit tests usually don't surpass a few lines.

Thanks Nikhilk
