### ISSUE TITLE
ScriptAlias problem

### ISSUE THREAD

**Issue by rekna1** [nikhilk/scriptsharp#107]
I am trying to implement something like jQuery.This, eg. <b>jQuery.This.Value("");</b> generates <b>$(this).Value('');</b>
and it is implemented by you as:

<pre><code>
[IgnoreNamespace]
[Imported]
[ScriptName("$")]
public sealed class jQuery
  { 
    [IntrinsicProperty]
    [ScriptAlias("$(this)")]
    public static jQueryObject This
    {
      get
      {
        return (jQueryObject) null;
      }
    }
}
</code></pre>

Now I wanted to implement <b>Javascript.This</b> (I need this in static methods where <b>this</b> is not available), I tried to implement the same way:

<pre><code>
    [IgnoreNamespace]
    [ScriptName("$")]
    [Imported]
    public sealed class Javascript
    {
        [IntrinsicProperty]
        [ScriptAlias("this")]
        public static Element This { get { return null; } 
        }
    }
</code></pre>

however, if I use it <b>JavaScript.This</b>, it generates <b>$.this</b>

What am I missing, why on the jQuery it is not emitting <b>$.</b> while on the Javascript object <b>$.</b> is emitted???

**Comment by nikhilk** [comment]
One quick thought/question - are you doing this inside an import assembly?

**Comment by rekna1** [comment]
Ok, moved it to an inport library, and now it works as expected.. thx..
Btw, I am also missing the defaultValue property for HTMLInputElements. This
is usefull for setting a forms input element to their default values (eg.
when you want to clear a form to its initial values) ... should I register
an issue on Github?

**Comment by nikhilk** [comment]
Yes, the missing defaultValue property should be a separate bug.

Also, it is exactly the simple type of thing that the community should just fork, fix, and create a pull request... no point waiting for such things. This is why the sources for all the import libraries were shared rather than wait for the full project.

Anyway, for now I fixed and checked it in (https://github.com/nikhilk/scriptsharp/commit/9d0926b616f7077220c22962fab2fadacbc5f37b) ... will be in the next build, but if you need sooner, you can create your own build of Script.Web.dll and use it now.

**Comment by nikhilk** [comment]
Fixed in 0.7.4.0 - ScriptAlias can be defined in the same assembly as the one being compiled and not just imported assemblies.
