### ISSUE TITLE
Copy references 

### ISSUE THREAD

**Issue by dmcweeney** [nikhilk/scriptsharp#110]
Hi,

I noticed the default behaviour was to copy the generated .debug.js and .js scripts from referenced projects to the output folder the current project.

This was causing me problems because I have the generated .debug.js and .js scripts in the project included in TFS so basically if I want to update them I need to have them checked out.

However when you were doing a build the generated scripts from referenced projects would try to be copied and if the target is read only the build fails - the read only attribute was being set from the source control.

I eventually got around this by updating the ScriptSharp.targets file - ScriptCompilerTask - and adding in the following param to the ScriptCompilerTask.

```
  CopyReferences="$(CopyReferences)"
```

And I have CopyReferences defined in my csproj file = false.

The ideal solution would be to use the CopyLocal attribute on the project reference to control wether the generated scripts should be copied to the build output folder or not.

Thanks

Donal

**Comment by nikhilk** [comment]
Coincidently, there were a few recent changes (that you'll see if you look at the history of commits) ... the msbuild task will update the target script file if it exists to remove a read-only attribute if set, before copying over. This change will be in the next release.

However I'd probably also add that you shouldn't add generated and copied/referenced scripts in script library projects into source control, since they're build outputs. I imagine you don't check in assemblies in the bin folders of a project, and the same should apply to scripts.
