### ISSUE TITLE
object initializers not supported?

### ISSUE THREAD

**Issue by rekna1** [nikhilk/scriptsharp#12]
Scriptsharp compiler does not support object initializers, is this planned in the future?
Basically, it would be very usefull for initializing jquery plugins the way it's done in javascript. As far as i can see (correct me if am wrong), when you define a class for custom options, it can only be inialized using the constructor 
(params object[] nameValuePairs) to get code like in javascript. But of course, one looses the intellisense which could be used if object initlializers would be available. This kind of limits the use of these option classes only inside plugins, not when calling them.

**Comment by nikhilk** [comment]
Yes, its planned for the future. It will be a little while though before its possible to handle c# 3+ language features.

For calling into plugins, you'd simply do:
FooOptions options = new FooOptions();
options.xyz = 123;

A little less optimal of course, but not impossible.

**Comment by josche-duplicate** [comment]
A really good alternative is having a Utility to parse and create a JSON object (or inline serializer). Have already needed something like this so you could effectively generate code like:
Script#
<code>
Foo foo = new Foo((FooOptions)Script.EmitJSON(new FooOptions(){xyz=123, abc=098});
</code>

Javascript
<code>
var foo = new Foo({'xyz':'123', 'abc':'098'});
</code>

**Comment by rekna1** [comment]
I think c#3+ language features should get high priority, as they would enhance scriptsharp quite a bit.

**Comment by nikhilk** [comment]
@josche:
If c# 3 syntax was supported, you'd just do

```
new Foo(new FooOptions { xyz = 123, abc: "098" });
```

In other words, you don't need Script.EmitJSON.

@rekna1
Another workaround is:

```
new Dictionary("xyz", 123, "abc", "098");
```

Yes, I agree c# 3 language features are super interesting. In addition to object initializers, auto-properties and extension methods are key features that would help a lot. I am closing this bug for now, as c# 3 support is going to be handled as a larger undertaking, rather than a tactical bug fix.
