### ISSUE TITLE
Generic class with open type causes fail

### ISSUE THREAD

**Issue by lboshuizen** [nikhilk/scriptsharp#127]
The compiler fails _without_ an error message.

The next example is not usefull but reproduces it

public class ResultSet < T >{
    public List < int > Items;
}

the above compiles OK but the following fails:

public class ResultSet< T >{
    public List< T > Items;
}

**Comment by nikhilk** [comment]
Right now declaring generic types is not supported. Same as the issue in #44.

You could create an import assembly as a workaround so you reference a generic type rather than declare one in script# compiled code, and create corresponding javascript to reference at runtime. For an example, look at Observable stuff in mscorlib.dll and mscorlib.js.

**Comment by lboshuizen** [comment]
Not supported is a pity but something to    deal with. No proper
message from the compiler is however some sort of pain.

Again, if I can lend a hand let me know!

On 24 nov. 2011, at 22:17, nikhilk
reply@reply.github.com
wrote:
