### ISSUE TITLE
Nuget packages for non-core libraries

### ISSUE THREAD

**Issue by michaelaird** [nikhilk/scriptsharp#165]
Can I propose moving the non-core libraries (jQuery, Knockout, etc) out to separate nuget packages? 

This would allow them to be rev'ed more often as these external libraries change and evolve. Also, ideally, these libraries could be maintained by the community so it would take the burden off Nikhil to keep them updated.

Thoughts?
Michael.

**Comment by nikhilk** [comment]
I think it makes sense for everything other than mscorlib.dll to be a nuget package. One question it raises...
How should the project templates be updated so that projects contain package definitions for referenced assemblies (like Script.Web, and Script.jQuery)? I am not sure how vstemplate files would need to be changed to deal with these assemblies coming from nuget packages instead. Do you know the answer?

I don't think they need to become separate repositories for folks to help though.

**Comment by michaelaird** [comment]
what about leaving them as part of the "core" since they're so key? Also, they tend to version less often.

**Comment by nikhilk** [comment]
Actually they update more frequently than one would imagine... there is always a metadata addition/fix happening. This page provides some information on the topic... http://docs.nuget.org/docs/reference/packages-in-visual-studio-templates

**Comment by nikhilk** [comment]
Done most of the work... of course need to finalize and publish the packages themselves.
