### ISSUE TITLE
Nikhilk - Can we contribute to Generic Support

### ISSUE THREAD

**Issue by andrewharry** [nikhilk/scriptsharp#177]
Hi Nikhilk,

Firstly - really appreciate scriptsharp - it has greatly increased my productivity.
Secondly - I'd really love to see generics included into the mix!

Can we help? is it particularly troublesome to implement?

Best Regards

**Comment by michaelaird** [comment]
+1 to this!

**Comment by nikhilk** [comment]
Soon enough ... I will be adding the core compiler code into the repository ... need to get my tests ported over from an internal runner into visual studio test project. Hopefully later this week.

The code has grown organically over many years now, and so I suspect this isn't going to be easy. Some parts could use an overhaul, but since the community is anxious I won't gate sharing by that effort, which I will continue on my end.

**Comment by andrewharry** [comment]
Brilliant!  I hope this really spurs on script sharp as a more flexible and dynamic platform.
Thanks again @nikhilk for all of your fantastic support and ingenuity

**Comment by DVaughan** [comment]
Script# is a great project. I too would love to see generic support.

**Comment by nikhilk** [comment]
If you'd like to see the current compiler's half-baked implementation, it is now in the repository. Better generics support will be implemented as the compiler is revamped (which I am working on, and will push as soon as feasibly possible), so closing this bug for now.
