### ISSUE TITLE
ASP.NET Ajax Support

### ISSUE THREAD

**Issue by KarlMaynardDK** [nikhilk/scriptsharp#181]
Is there any chance we can get this back so we can use the either the mail scriptsharp core OR the Microsoft ASP.NET Ajax core - right now i am working on an import library for the Telerik RadControls and the current mscorlib.js doesnt work with the telerik controls which rely on the MS Ajax core.

I know this used to exist and i have heard the arguments for using jquery instead, however, i think both options should be supported.

Or, as a minimum, is it possible to update the scriptsharp core so that its methods match the latest asp.net ajax script.

The problems i am being caused by the Type class in the scriptsharp mscorlib.js.

**Comment by nikhilk** [comment]
Realistically, no ... this is super unlikely... esp. the part about making mscorlib match what is in the msajax script, or maintaining multiple codepaths in the compiler.

I will try to get the old sources for the msajax library so you can avoid re-writing the import library - don't have access to my archives right now, since these were on an older machine that has since been repaved... but I'll look for it. However, there is no guarantee it will compile with the latest builds, or work with changes going forward.

I completely realize this isn't ideal from your perspective, but maintaining support for this technology that has long been supplanted for better options isn't productive.
