### ISSUE TITLE
Missing ImageElement Constructor

### ISSUE THREAD

**Issue by henkosch** [nikhilk/scriptsharp#187]
Hello!

I want to load images dynamicly and draw them on a canvas with Scriptsharp. 
This is how I would do that in javascript:

var img = new Image();   // Create new img element
img.onload = function(){
  // execute drawImage statements here
};
img.src = 'myImage.png'; // Set source path

See: https://developer.mozilla.org/en/Canvas_tutorial/Using_images

It turns out that the Image() constructor actually creates an ImageElement object, but I couldn't find that constructor in Scriptsharp. So how can I create an image element on the fly? Do I have to attach a hidden image tag, because that's just creazy. 

For more details about this constructor see the specs:
http://www.whatwg.org/specs/web-apps/current-work/multipage/embedded-content-1.html

[NamedConstructor=Image(),
 NamedConstructor=Image(unsigned long width),
 NamedConstructor=Image(unsigned long width, unsigned long height)]
interface HTMLImageElement : HTMLElement { ... }

Any ideas?

Thanks,
Henko

**Comment by nikhilk** [comment]
Does document.createElement('img') without adding to the DOM get the some results?

The fix is pretty straightforward if you're up to doing it (and submitting a pull request). In https://github.com/nikhilk/scriptsharp/blob/master/src/Libraries/Web/Html/ImageElement.cs ...
- Make the ctor public
- Add a [ScriptName("Image")] attribute on the class.
