### ISSUE TITLE
Constructor parameters are not minimized

### ISSUE THREAD

**Issue by jimmygilles** [nikhilk/scriptsharp#198]
Hello,

In the javascript "release", I see that the parameters of the constructors are not minimized.
That would be great to have to reduce the size of the javascript.

Thanks.

**Comment by nikhilk** [comment]
Going forward minimization is handled by a minimizer, and the role of the compiler is to produce minimizable script, i.e. use patterns that complement the minimizer.

So no need to minimize parameters... which ultimately results in (typically) parameter names that use a single letter, rather than the longer $p0, $p1, ...
