### ISSUE TITLE
0.7.5 Release?

### ISSUE THREAD

**Issue by michaelaird** [nikhilk/scriptsharp#204]
How close are we to a 0.7.5 release? is there anything we (the community) can contribute to help knock things off the list?

**Comment by nikhilk** [comment]
I am hoping to include as part of 0.7.5 a switch to nuget + vsix as the way to distribute script# releases. I've done some early investigation, but help on the investigation and making this happen will bring 0.7.5 out sooner.

General idea -
- A [required] script# nuget package for the core compiler, msbuild target file and mscorlib.dll.
- A vsix extension that contains projects along with the required nuget package and powershell scripts to add/update the targets import reference in the csproj.
- A set of optional nuget packages for each import library.
- A nuget package for use within web projects to install scripts like mscorlib.js.

In order to move away from an msi install-based approach, also need to find an alternative to the single file generators associated with resx files, since they require registry-based install. Thinking of a single T4 template within the project to convert all resx files into c# source that works with script# ... needs some investigation here as well.

If any folks have experience with bringing together nuget, vsix, powershell scripts, that would certainly help. Thanks for asking!

**Comment by michaelaird** [comment]
OK. I'm not an expert in any of these but I'll have a look. At the very least, I think i can contribute nuspec files for the import libraries.

**Comment by nikhilk** [comment]
I'm starting to make some progress on this - at least on bullet #1. #1 and #2 and T4 are the ones where there are things to figure out. Once that is in there, will be good to see progress on #3, which should hopefully be straightforward.

**Comment by ranc** [comment]
Can't you please release 0.7.5 now we really need updates!
could  you include those in the next one?

**Comment by nikhilk** [comment]
These are almost done... if you see the recent commits. So hoping to put out new bits very soon.
Is there a particular fix you're interested in ... if you're able to clone and build locally, and verify its got the fix, that might help.

**Comment by ranc** [comment]
Thanks! we are eager to see. Keep up the excellent work!
