### ISSUE TITLE
Language features

### ISSUE THREAD

**Issue by levi2** [nikhilk/scriptsharp#222]
Hey guys,
for starters i really love what you are doing here.
we use script# for a year now and are extremly happy.

besides if this is the wron place to post this.
if so feel free to just delete this "issue".

anyways here are my questions / issues.
1. will there be support for auto properties?
2. will there be support for overloadeding methods ?
    like void a(string a){} and void a(string a, string b) {} in the same class?
3. will there be support for different namespaces within one script library?
4. will there be support for tuples ?
5. will there be support for using "var"?
6. will there be support for automatic constructors? like new SomeClass() {properyA = "some", propertyB = "some1" };
7. will there be support for something like system.treading.wait(x); 

1-6 are, to me, the mayor language issues "missing".
7. well : ) .... 7 would be just too awsome i guess.

anyways please dont consider this as a complaint or anything like this.
i admire this project and would just love to know when/if i might expect these features.

so any answer is appreciated : )

best regards, 
 levi

**Comment by nikhilk** [comment]
There is work started to support these features... hope to share and open for contributions as well as soon as the basic infrastructure for up-to-date language support is in place. Thanks for the interest!

**Comment by levi2** [comment]
I see.
thanks a lot for the quick answer.

all the best wishes,
 levi

**Comment by levi2** [comment]
hey,
could money help reaching theese goals faster?

**Comment by levi2** [comment]
well i guesst not ; )

again.
all the best wishes,
levi

**Comment by danelkhen** [comment]
If it helps you can try SharpKit, which supports all of your requested features:
http://sharpkit.net

**Comment by levi2** [comment]
ZOMG
i did not know this existed !
thanks a lot !!!

is there a significant downside in comparsion to scriptsharp?

**Comment by levi2** [comment]
furthermore....
sorry to ask this here but why script# at all if there is the exakt tool for the task but way more sophisticated?

**Comment by jsfsn** [comment]
@levi2 You visited the SharpKit site, right? It's not open source nor is it free.

**Comment by levi2** [comment]
yes of course i saw that, but to be honest, that would be the least of my problems.
i ment downsides tech wise.

or are you suggesting script# was made just to give an open source alternative to sharpkit?

**Comment by jsfsn** [comment]
I do not know the origin of Script#, or the authors reason for it, but it is an alternative to SharpKit and it has been serving us and many others quite well AND it is open source. SharpKit seems good, but to question the existence of an open source project and compare it with a closed sourced, commercial, alternative?

**Comment by nikhilk** [comment]
This discussion no longer qualifies as an issue discussion. So lets stop what @danelkhen started here, and call it that. OK? I am not dismissing the debate, but there is probably a better forum for it than this one.

For the record, Script# existed since 2005 (to my knowledge, it precedes other similar tools) as my personal project and has continued to be a "labor of love" ... part time project and I've had the pleasure of seeing many large and small projects built on what it does, despite its missing features. I do hope to continue working on it, and have some ideas for future directions, as well as addressing some key language features that are in the must-have category.

I didn't respond to the money question - honestly I'd approach this project pretty differently if that were the case, besides the fact that it could be at odds with what I do for work if I went down that path. :-)

**Comment by levi2** [comment]
i am sorry if my questions came through like that.
since i am not a native speaker i might have expressed it wrong.

what i wanted to know was the reason to create script # since i thought that there might be a significant downside (except the money issue) to sharpkit.

ps.:
nikhil could you point me to a place where i can talk about this?
could i maybe contact you on skype?

sorry for stirring dust up guys. i did not mean to be offensive

and as in my above comments...

all the best wishes,
 levi

**Comment by nikhilk** [comment]
Since you ask for the reason for creating script# - I worked as dev and architect on asp.net and the Ajax framework we were developing in 2005 (early ajax days), and I figured there is a better way to deal with scripting for the limited framework of ~15K lines of script, and even more so for the many ~100K lines of code making up complex apps. So I took on the task/challenge to find a better way, and shared the results ... the intro post if you're interested is at http://nikhilk.net/ScriptSharpIntro.aspx.

No problem about the questions you asked. I just don't want this forum to be a discussion ground for related projects. I know they exist... they all likely have their unique pros/cons. Its great there have been multiple attempts to solve the scripting problem, both oss and commercial.

@levi2 - you can reach me via the contact form on my site at http://www.nikhilk.net.

**Comment by levi2** [comment]
thanks!

i dont find this a good place either. and i totally agree on the view on multiple solutions.

thanks for the contact info.
you have a looong mail now ; ) ... thanks for your time
