### ISSUE TITLE
RequireJS Support

### ISSUE THREAD

**Issue by dealproc** [nikhilk/scriptsharp#226]
Not sure if this is an issue as much of a question... would something like RequireJS be worthwhile to build a tooling for within the Script# libraries?

**Comment by nikhilk** [comment]
Plan is to have script# produce scripts to the AMD pattern. In the mean-time you might be able to manually achieve it, using the script template associated with each script# project (its there when you use the project template - for example, see https://github.com/nikhilk/scriptsharp/blob/master/samples/AroundMe/AroundMe/Properties/Script.template).

By default it contains:

```
(function() {
#include[as-is] "%code%"
})();
```

You could change it to anything:

```
define('myscript', [ 'dep1', 'dep2' ], function() {
#include[as-is] "%code%"
});
```

The part that is missing is to use the 'required' dependencies rather than depending on the assumption that dependencies have added their APIs to the global namespace.

Also, ideally the compiler would pull the name of the current script and the dependent scripts from the c# source. This is where the Name property of the ScriptAssemblyAttribute comes in play that exists in every script# project. Right now you can get hold of them in the template, but they're not necessarily exactly usable as-is for module loading. Anyway, as example, your script template could be:

```
(function() {
function defineScript(name, dependencies, script) {
    define(name, dependencies.split(','), script);
}
defineScript('#= Name ##', '#= ExecutionDependencies ##', function() {
#include[as-is] "%code%"
});
})();
```

Hope that gives some ideas. Its not fully there yet...

**Comment by dealproc** [comment]
Well, can we use the references in the c# project somehow to generate the list of dependencies?  We are already referencing them to get the syntactic sugar, so that feels like the logical way to handle.  The referenced assembly should be checked for the attribute that you mention above to decide if the referenced name should be the namespace, or if it should be a custom name you provide in the attribute.

As far as the name is concerned, it would seem most likely that it should equate to the name of the dll overridable by the attribute you talk about above.

**Comment by nikhilk** [comment]
Mostly done on my end - will be committing this hopefully this week with some other cool improvements and additions all around, and new . Thanks for waiting.

**Comment by dealproc** [comment]
Wicked.  Will be glad to be able to look at that, and learn more about how to utilize the AMD methods.

**Comment by dealproc** [comment]
@nikhilk Are you looking into other items, like Sammy.js, or looking toward the rest of us to implement those libs for use?  Asking because next steps, once the app is "running", is to use something like Sammy.JS or similar to give routing to the Url.  I noticed that there's a jQuery.History lib, but it seems like the *.js that it supports is EOL'd, so would rather use a tool that is still active.

**Comment by nikhilk** [comment]
Right now focusing on better script generation and c# language support, and some new scenarios... so I would really appreciate folks helping build import libs for common stuff (like you're doing with bootstrap). I can help along the way as needed with both guidance as well as supporting compiler work when needed.

As far as history goes, yes need to look into better history library. Needed to look into History.js... which offers low level stuff ... and then there are higher level libraries that provide routing/mvc patterns. I haven't investigated the latter, so don't know about any specific ones... though backbone comes to mind. I hadn't heard about Sammy so need to check it out. Found this interesting link - http://codebrief.com/2012/01/the-top-10-javascript-mvc-frameworks-reviewed/

I had also started dev on a framework myself (mvvm, ioc, templates, declarative behaviors etc.) ... need to get back to it once I have these big script# revs completed. Check out my other repository named Sharpen if you're curious.
