### ISSUE TITLE
Link Project to Web Application

### ISSUE THREAD

**Issue by dealproc** [nikhilk/scriptsharp#236]
@nikhilk I recall back from when this was shown at Mix11, that when you created a new Script# project, you were prompted to link it to your web application, and it would do the requirements necessary to get the project going in the web app.  Do we have any way of re-enabling that?

**Comment by michaelaird** [comment]
I think for now, you have to do it manually by editing the scriptsharp csproj file and adding this element

```
<DeploymentPath>[relative path]</DeploymentPath>
```

**Comment by nikhilk** [comment]
Yes, the underlying mechanism still exists. I had to remove the custom vs file new project wizard template in favor of the nuget package installing one, that installs default packages into a new project.

What I'd love to see is a VS addin of sorts that can edit various script# specific project properties... there are a few others besides DeploymentPath.

If anyone is seeing this, and would love to help make this happen, that would be awesome.

**Comment by dealproc** [comment]
right... but that isn't going to create the references in the project, or am I misunderstanding this?  My thing is that, IIRC, the way it worked as of Mix11, when you did the whole "Create Project" thing, it also created the links to the file outputs you put into the <deploymentpath /> element, no?

Again, I'm new to this, so forgive me for any misunderstandings... just trying to get a grasp on things.

**Comment by nikhilk** [comment]
No problem at all for raising questions.

The previous behavior simply initialized the DeploymentPath property in the csproj. The script# build task would copy generated files over. There weren't any real links or references that it setup, i.e. you would have to ensure you built the script# project to have that copying happen.

However that addin I alluded to above would/could in addition setup project "dependencies" in the solution so building the web app would auto-build the script# project. Note this is still slightly different from references. A web app project shouldn't "reference" a script# project since it doesn't consume the assembly resulting from the script# project.
