### ISSUE TITLE
Javascript best practice pattern for classes

### ISSUE THREAD

**Issue by rekna1** [nikhilk/scriptsharp#26]
I've just learned about a best practice for javascript classes , to avoid namespace collisions and handling private and public variables and fucntions, and I really like the pattern. I was wondering how I could port it to scriptsharp. The pattern is the following:

```
(function(myobject,$,undefined) {
   // private variable
   var privateVar = true;
  // public variable
 myobject.publicVar = "some public var";
  // public function
  myobject.doSomething = function() {
        addItem("test");
        additem("another");
  };
  // private function
  function addItem(item) {
      if (item!=undefined) { console.log("adding"); }
  }
} (window.myobject = window.myobject || {} , jQuery ));
```

I can create the part

```
 (fucntion (myobject,$,undefined) { 
    ...
} (window.myobject = window.myobject || {} , jQuery ));  
```

perfectly with the .script file in the properties folder of my project.

public function can be added perfectly when I decorate my class with

```
[Mixin("myobject")]
```

and adding a static function.

But static variables are not allowed on Mixins, so I cannot create a private variable or public variable and a private function is translated to 

   myobject._addItem = function myObjet$additem(item)  { ... }

I know this pattern is somehow different from the one scriptsharp now implements, but , it allows for true private variables and functions, not just by convention and by enforcing access through the scriptsharp compiler... because if one writes a class that can be consumed by none scriptsharp code, private variables / functions are still accessible.

I was wondering if you might consider this type of pattern, perhaps by using a special attribute to give the user this option of creating code.

**Comment by rekna1** [comment]
BTW .. I would really appreciate if you (or some else) could write a reference on all the current attributes in Scriptsharp, explaining their use and how they affect script generation. I think it will be usefull for a lot of scriptsharp users, currently, I constantly forget what their use is, and find myself constantly trying to figure out what they do by trial and error. Some are described in Scriptsharp.pdf, but not all, and it would be usefull to have some kind of reference listing all available attributes and their use.

**Comment by nikhilk** [comment]
Script# uses the prototype model for emitting classes, as opposed to the closure model, as it is much more optimal - you don't create instances of members for each instance of an object.

However, the way script# will emit code will change significantly over the next few releases, so code minimizes better, while staying true to the prototype approach. It will make private methods private, but member fields will remain on the instance. I will share a general outline of what the emitted code will be like and take comments/suggestions around that.

This sort of stuff is unlikely to be customizable at a fine-grained level, esp. considering the number of variants out there of defining classes each with their own pros/cons and personal favorites. Too much flexibility brings about more complexity than worth it. The approach for the script# compiler is to find a model that is a fair balance between original source code, and good runtime characteristics, rather than optimize for any one syntax and OOP simulation. Using script# implies you are focused on _your_ code, rather than the OOP simulation (assuming of course it is correct in terms of semantics and reasonable in terms of perf).

I suppose there could be a general purpose extensibility point to allow one to write their own generator and take over things completely (assuming that will actually work), but that is going to require someone to write a fair bit of code, making it less compelling, and hence pushes such work down the priority stack.
