### ISSUE TITLE
Unable to access to the module registry (list of loaded module names) in 0.8

### ISSUE THREAD

**Issue by john-pennington** [nikhilk/scriptsharp#287]
0.8 marks a dramatic shift in the way scripts are compiled and loaded, with the support for AMD and a clear focus on avoiding JS global scope pollution. All great stuff.

However, the runtime has been written in such a way, as far as I can tell at least, as to "hide" the registry of modules that are loaded and in-play. Interrogating the runtime library, I can see what appears to be a private member that stores such information inside of ss which appears to hang off of global scope when no specific module loaders are used, but I can't seem to walk my way to that list programmatically. In 0.7.5 and below, accessing the equivalent of this registry meant accessing a list of namespace names that the runtime was aware of. Getting at the list was a matter of entering through JS global scope into specifically named objects... I recall the object I am thinking of as "__namespaces" but I could be corrected.

The point of accessing the loaded namespaces at runtime is that code could walk the tree of loaded types. Although doing this was relying on an implementation detail that gave access to the root namespaces and all children thereof, it enabled key features that I have written into my HTML5 application platform (from trivial to complex, each feature utilizing those before it):
1. Runtime type interogation/browsing
2. Reflection
3. Method Interception
4. Dependency Injection
5. Code Contracts with Runtime Contract Rewriting

Nikhil, would you consider providing an API off of the global ss object that exposes the list of loaded module names, with the understanding that this list is temporal and is subject to change between calls due to the ability to load more modules at runtime?

Or if this is already exposed, could you enlighten me on how to get at it?

Excellent work with S#, don't stop!

**Comment by nikhilk** [comment]
The feature you're asking for certainly makes sense, and you're right, in previous versions mscorlib touched/added globals (including __namespaces) which made this possible.

Would this be as simple as having an ss.modules method that provides access to the list of loaded modules? Once you have the modules you can enumerate them to find functions and their prototypes (for types/members) and objects (for enums/resources). I'd rather structure the model in terms of modules, since namespaces are pretty much at this point a code organization technique at the c# level, rather than a concept at runtime.

Incidentally (and tangentially related to this topic) is the changed inheritance model. The new approach allows one to mixin members onto the prototype of a base class and have those show up on derived types, after the inheritance hierarchy is setup. Previously the mixins would not have been available on derived types. Its related to method interception in your list as well as rewriting.

**Comment by nikhilk** [comment]
Continuing the thought process - 

There are actually two lists of modules to think about. The list of modules defined using script# (via the ss.module runtime api, i.e. stuff typically generated by script# compiler) and the other is the list of modules loaded by a script loader.

The former would match what was possible with __namespaces, and can be implemented.

When thinking about the latter, there isn't anything in the AMD pattern or CommonJS pattern to provide a list of loaded modules (as far as I know). I can certainly add something to the script# implementation of AMD (in ssloader.js), but if this is of interest, then its really up to the loader (of your choice) to provide access to it.

**Comment by nikhilk** [comment]
Made changes to enable accessing the first list of modules (the ones created using the ss.module api). See commit - https://github.com/nikhilk/scriptsharp/commit/922683af8d99eb7d8040ed335745e548a86d475c ... if you can look at the diff to see if it works let me know if that takes care of this suggestion.

Also, its not yet incorporated into a build, but you can sync and build if you'd like to go further and start using it as well.

**Comment by john-pennington** [comment]
Hey hey I did not expect such a quick response! Thanks very much for considering this Nikhil.

I looked at the diff and your implementation appears to meet the requirements we formulated in this thread. The opening up of the first list of modules (ss.module api loaded/provided modules) enables a lot of powerful features for platform writers, and I thank you for that.

Thanks also for the info regarding the changed inheritance model and the "live-ness" of mix-ins. I wasn't aware of that and it will help guide a port of interception features of my library to 0.8.

Perhaps if you are interested I can contribute some of those features as a distinct concern/library/module over the top of the core S# runtime (maybe a seperate GitHub project), fold some of it into your SharpenFX (revive, refactor, or continue that project), or sink some of it into the core API and runtime, depending on where you consider such features to be most appropriately layered in. My personal feeling is that the core runtime should be tight, and that it would be nice to have a comprehensive set of "platform" features in as many unique modules as makes sense but while also being delivered in as few channels as possible (one or a few), with SharpenFX being an opportunity to lead the field.

I am new to the AMD pattern and still trying to orient myself around its concepts. I understand the change of "compartmentalization" at runtime from namespaces to modules, the differences in those concepts, and why it was done. I am a little hazy on the dynamic nature of modules and the ability to load them as needed, which isn't a S# concern so much as it is a JS concern.

However, is my understanding correct if I were to say?
1. The first list of modules, the ones exposed through this new API, could be considered "statically loaded" by their definition somehwere in JS code (and as is done throught the ScriptTemplate attribute in 0.8 when S# project types are created).
2. The second list of modules, the ones that can't be interrogated at runtime, could be considered "dynamically loaded" via programmatic invocation of script loader APIs (of which ssloader.js is one) at runtime.

If my understanding is correct, I think there is the potential for value in one or more of the following:
1. Extending ssloader.js to open up access to the second list for S# consumers that leverage this particular loader.
2. Finding a way to unify the first list and the second list (if it exists by way of choice of loaders) into a common API that is available in the core ss, perhaps just folding into the recently developed API, or augmenting the API to return a Tuple or made-to-measure data structure that indicates both the module name and whether it was dynamically loaded or statically defined.
3. Providing some sort eventing mechanism out of the unified API in (2) so that registered listeners can synchronize themselves even in the face of a dynamically-loaded environment.

Of course that value has to be weighed against the opportunity cost to develop it, as well as its practical use. Nikhil, if you see that there is an opportunity here, I would be happy to open a seperate item for it so we can close this one out. We can let the wider S# community weigh in on it there. If not I'll close this one out anyway.

**Comment by john-pennington** [comment]
Also, I will definitely pick up the source and use it ahead of release, both to verify it against my understanding and to get a jump on porting some of my platform libarary features to 0.8.

Thanks again Nikhil.

**Comment by nikhilk** [comment]
Several points here ... hopefully I'll address them all:
- Agree, I want to keep the core library extremely small. So additional optional features should be separate, esp. since there are tools that will allow combining previously separate modules of functionality. I am sure more might show up into the core, but everything needs to meet a high bar.
- Dependency injection is interesting. Note that Sharpen does have a pattern for IoC and ability to defer to a factory method to resolve dependencies. Anyway, would be interesting to see what features are most valuable... and ask to see if others have opinions. Thats probably best way to start and then potentially sharpen, or other similar frameworks/projects layered on top of script# will be the best approach.
- Dynamic modules ... modules can be loaded dynamically (in AMD via either require or define calls) at any time. 
  You can even turn a dependency module from pre-loaded to dynamically loadable in script#. By default dependency modules are pre-loaded (by virtue of showing up in the list passed to define in the generated script). However through the use of an assembly level ScriptReference attribute, you can specify a particular module should be delay loaded. It is then up to the code to use Require programmatically to load a module at a certain time.
- Extending the AMD loader in ssloader - this could also surface loaded modules, but there are some things to keep in mind.
  - in general the structure of a module is arbitrary. A script# generated module is predictable, but for example if you look at jQuery or some other random module, you'll see fairly large degree of variance. This affects what you can generically do through introspection.
  - unification can be done, but its a bit more complex - the scripts don't have dependencies on each other. ss.js doesn't care about the script loader used (or even require one), and ssloader.js by definition is independent.
  - eventing etc. need to think about this some more. I don't think I have seen this in any of the AMD related stuff I've seen. I suppose a lot of this is organically evolving ... from the module pattern (there are two at least) to module loaders, and their functionality. Also module loading events could make sense in the browser, and less so in an alternate environment like nodejs (I think ... unless you start replacing the built-in require functionality I suppose).
