### ISSUE TITLE
Renaming a class breaks intellisense

### ISSUE THREAD

**Issue by michaelaird** [nikhilk/scriptsharp#290]
I was just wondering if this happens to anyone else and if there's a solution.

If I rename a scriptsharp class in VisualStudio 2012, intellisense breaks for that class. I can compile without errors but Visual Studio will give me the "red squiggles" and say it can't find the type or namespace. Closing and restarting Visual Studio **does not** resolve it. i end up having to reboot to fix it.

is it just me??

**Comment by nikhilk** [comment]
I've never seen this. There is really nothing script# specific in the IDE editing experience... its just a c# project.

**Comment by john-pennington** [comment]
I have seen this in VS 2012 as well, both for 0.7.5 and 0.8 S# projects. The C# code editor gets confused when certain project or refactoring operations happen. There have been occasions where directives (#if DEBUG for example) get confused as well.

I have not found a way around other than a reboot as well. Something deep in VS is going wrong. Sorry I don't have a fix, but you are not alone.

**Comment by nikhilk** [comment]
Does it happen in script# projects only, or other c# projects as well? As mentioned above as far as the IDE is concerned, its just a c# project. Unless it has to do with a custom mscorlib assembly, though that is very much a supported scenario.

My only thought is to try and a) get more concrete data/reproducible steps, and with those, b) follow up with c#/vs ide folks on the appropriate visual studio forum.

A reboot is pretty drastic. Maybe deleting the obj and bin directories and restarting vs would also reset whatever state vs is getting into. A bunch of ide operations rely on temp assemblies in the obj directory. I can't imagine what vs state besides that sticks around across process restarts that requires a full reboot to go away. Strange indeed...

**Comment by john-pennington** [comment]
Hey Nikhil, I agree this that this is an IDE issue, not a S# issue. I have not seen the same in C# projects, however I have seen the IDE delay "activating" language code helpers such as keyword hilighting for C# files in C# projects, even if only by a few seconds. Conjecture is that the code editor is activating such helper services asynchronously so that it can load and display at least contents of the file quicker.

A seperate but interesting issue is that VS2012 "forces" the System.Core assembly to load in each project at development time, whether there is an explicit project reference or not. I imagine the IDE team considered the System.Core assembly to be of such importance that it should be accessible to code writers even without explicit inclusion, probably becuase it defines the extensions that implement the core of the LINQ pattern, and they wanted this to be discoverable without any work on a developers part. System.Core being defined as a seperate assembly instead of being implemented in mscorlib.dll feels like a result of the "red bits/blue bits" constraint the framework authors had when organizing new parts of .NET 3.5, although this is a guess on my part. The auto-load behavior has the unfortunate side effect of exposing APIs through intellisense that should not be exposed to S# projects, and runs counter-intuitive to the concept that mscorlib may be freely replaced or ignored at both development time and compile time, which S# takes advantage of to great effect in the tool chain. Searches around the web for a solution to this problem (forcing VS to no longer force-load System.Core at development time) have not born any fruit.

I **think** I have done a clean on the solution to try to get the editor back in line but this did not appear to help. I must admit I haven't been intentional about the remediation steps taken when it all goes wrong, and knowing the exact steps to break and then fix the code editor is probably our only hope at raising an addressable issue with the IDE team. I do know that restarting VS by itself doesn't correct the issue, and this jives with the "interim obj files may side-effect the code editor so try sweeping them" you mention above.

**Comment by michaelaird** [comment]
It seems to only happen in script# projects but I agree that it's likely a
VS issue. I wonder if it is related to loading System.Core as John
mentions. I'll try to keep a close eye on when it happens and what led up
to it.

**Comment by aschoenebeck** [comment]
It happened to me too. I moved one ScriptSharp class .cs file to a different folder and changed its namespace. Then VS 2012 intellisense lost track of the class. Rebooting did not help.

I fixed my solution by deleting the obj and bin folders as well as the toplevel <solution>.v11.suo file.

**Comment by john-pennington** [comment]
Thanks aschoenebeck and Nikhil, your insight into the cause and the fix for the problem was informative. The problem definitely appears to be associated with the obj directory and its use by VS to provide intelligence to the code editor.

I have distilled the fix steps from aschoenebeck to the following:
1. In the project exhibiting the intellisense errors, delete the obj directory. This can be done directly in the VS Solution Explorer if "View All Files" is toggled.
2. Unload and reload the project. In the VS Solution Explorer, these commands are available in the context menu of the project node.

When the project reloads, the code editor should be back in sync.

Nikhil, is Connect the best way to surface this issue with the VS team? Is Connect still around, or is there a better feedback tool that you are aware of?

**Comment by theoutlander** [comment]
Thanks, that worked!!
