### ISSUE TITLE
Parallel building in VS2012 yields Unable to copy referenced script  errors

### ISSUE THREAD

**Issue by reymarx** [nikhilk/scriptsharp#292]
VS2012 performs parallel building with a maximum value of 8 by default (configurable in the Build and Run options).

Building a solution containing multiple script# projects will hit some race conditions when copying scripts from referenced projects and will fail with one or more errors like:

**Unable to copy referenced script 'RefProjectPath\bin\Debug\refScript.js' as 'DeploymentPath\refScript.js' (The process cannot access the file 'DeploymentPath\refScript.js' because it is being used by another process.)**

It seems that the compiler will try to overwrite files that already were copied to the _DeploymentPath_ and it can do it with the same file from several projects.

Is there a way to disable copying the scripts for the referenced projects, and copy only the specific one for the project being build? I really like the idea of taking advantage of building projects in parallel.

**Comment by briantoba** [comment]
I can repro this as well.

**Comment by nikhilk** [comment]
Unclear what needs to be done - feel free to check out the sources for the msbuild task and see what can/should be done. If the file copying work should fail in any one instance of the task, that is a failure as far as that task instance goes, and should be reported as one... otherwise in some other scenario, a failure will go undetected.

Check out the msbuild targets file ... you can turn off copying by setting CopyReferences to false... if that works in your scenario.
