### ISSUE TITLE
Error on saving entities using breezejs(missing ScriptAssemblyAttribute)

### ISSUE THREAD

**Issue by ZiadJ** [nikhilk/scriptsharp#294]
ScriptSharp is conflicting with Breezejs:

http://stackoverflow.com/questions/13654416

It also conflicts when the WebActivator dll is referenced.

**Comment by nikhilk** [comment]
Don't add a reference to a script# assembly in a non-script# project. The mscorlib in script# contains various APIs that make sense for script, but not for .net projects.

**Comment by ZiadJ** [comment]
Ok, but has this been mentioned anywhere before?

**Comment by Sam7** [comment]
I think this is still an issue, since I need a reference to my script projects in order for my scripts to be copied into my web project.
WebActivator now, looks through all dlls in the bin directory and throws a 
Could not load type 'System.ScriptAssemblyAttribute' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
Even though I haven't directly referenced the script mscorelib in my web-project.

I guess the question is, whether it would make sense that any schript dll would be delete from the bin directory of the web project during the build process.

**Comment by kirakosyan** [comment]
Now the same problem I can see with SignalR

**Comment by theoutlander** [comment]
Have you tried setting Copy Local to false as mentioned in https://github.com/nikhilk/scriptsharp/issues/424?
