### ISSUE TITLE
Newbie Looking to Dive In

### ISSUE THREAD

**Issue by Mike-E-angelo** [nikhilk/scriptsharp#299]
Hello All,

Interested in Script#... it is more aligned with how I would imagine a "JavaScript Library" to exist in .NET... TypeScript seems to have missed the mark.

I'm looking to get v.8 working on my machine.  It doesn't appear to exist in NuGet.  Is there guidance somewhere to get this working?

Thank you,
Michael

**Comment by Mike-E-angelo** [comment]
Nevermind, found what I was looking for. :)
https://github.com/nikhilk/scriptsharp/wiki/Building-and-Testing

**Comment by nikhilk** [comment]
Feel free to ask any questions that come up.

I need to publish the 0.8 vsix and nuget packages... at this point I think enough folks have started using it to create some sense of confidence in the fairly significant changes introduced since the last build. Once that happens, it should simplify the flow a bit.

**Comment by michaelaird** [comment]
Nikhil,

What about publishing the 0.8 vsix and nuget packages as "pre-release" so
people can try them out?

**Comment by nikhilk** [comment]
As far as I know vsix doesn't have a "pre-release" option, but that is something to look into using for the next wave of changes for the nuget packages themselves.

**Comment by Mike-E-angelo** [comment]
One possibility is to include the .vsix in the pre-release NuGet package, and open a ReadMe.txt upon installation that mentions to install it... or maybe even try installing the vsix from the NuGet installation...

**Comment by michaelaird** [comment]
Is the 0.8 vsix incompatible with the 0.7.5 nuget packages?

**Comment by nikhilk** [comment]
The 0.8 vsix contains project and item templates that reference 0.8 nuget packages.

**Comment by michaelaird** [comment]
Hmmm...is it possible to have different versions of a vsix installed side
by side?

**Comment by nikhilk** [comment]
No, it doesn't as far as I know. Would need to publish every version with different id/name. Also every template would have to be qualified with a version.

Note that we're only talking about templates to create _new_ projects. Your existing projects referencing older nuget packages would not be affected.

**Comment by theoutlander** [comment]
@nikhilk - I'd suggest that we iterate and (pre?)release more frequently given that a lot of useful features have been built in the last few months but they've taken way to long to make it into the branch given how fast other technologies are changing. I like the fact that the risk with S# isn't like other products because all it does is generate a JS file which we will test locally before putting it into production, so there won't be surprises.

On a side note, I'd like to help out with documentation (more like an e-book) since I'm using S# on two large projects (and used it on OWA in the past) and I've ran into several issues just getting off the ground with many of the new features. At times the examples weren't adequate. We could create a separate Github project or a section in this one. I can drive some of that if I could get some direction from you. Let me know your thoughts.

**Comment by nikhilk** [comment]
Hey Nick - ping me at nikhilk at live.com ... lets discuss. Have couple of things on my list for the year end ... both getting this release done (agree, taken way too long) and getting a couple of intro docs done.

**Comment by Mike-E-angelo** [comment]
I have to say there's a lot of promise and potential here.  I looked into TypeScript and was rather disappointed in its implementation (not to mention vision).  I just got out of 6 years of Xaml-based development in Silverlight/WPF (and yes, even included your Silverlight.FX in my framework at one time, nikhilk).  I investigated Xaml Windows Store Applications, but Windows Runtime doesn't even support Markup Extensions!  Couple this with the (still aching) heartbreak of Silverlight strategy shift, and I am ready to explore something else that effectively allows me to "develop once, run everywhere."

So with that, I'd like to help out anywhere I can.  Xaml developers hate having to work with JavaScript.  Obviously, that's what's so appealing with Script# is that you're working with native C#.  Pretty cool. :)

Anyways, I hope to research and dig into this project and help out in any way that I can.
