### ISSUE TITLE
Comparing with null behaviour changed in 0.7.1

### ISSUE THREAD

**Issue by volkanceylan** [nikhilk/scriptsharp#31]
ScriptSharp was compiling if (obj == null) and if (obj != null) statements to same expressions in javascript (and i think it was correct) but now it produces (!obj) and (!!obj). If obj has some falsey value like 0, these comparisons may no longer mean what we understand comparing with null should mean in C# (it should give true if obj is undefined or null). People like me have lots of code depending on this check. It may break existing code badly. Please introduce something like Script.IsFalsey, Script.IsNotFalsey etc for those who wants to use this new behaviour and keep old one consistent.

**Comment by nikhilk** [comment]
The old generated script used "==" and "!=", i.e. it was already a loose equality check when comparing to null. In other words, the prior behavior did not produce "===" and "!==", which is the way to get strict check for null. The way to do that was (and is) Script.IsNull. Same goes for undefined with Script.IsUndefined.

I take your point about matching c# source code in generated script code, but can you validate if there is actually a meaningful behavior change?

Side note - it would actually be great (and useful) if this sort of discussion happens when another bug asking for this change was opened by another user ... all the bugs are opened and listed publicly here so there can be such discussion.

**Comment by nikhilk** [comment]
As a reference, here is the issue that prompted the change:
https://github.com/NikhilK/scriptsharp/issues/27

**Comment by volkanceylan** [comment]
Sorry, you are right, i should have commented in the other issue, but it was closed and didn't notice it is related to this change.

I understand that issue, and that's why i said there should be some method like Script.IsFalse, Script.IsTrue etc. But in C# we can't write such shorthand if statements for variables other than boolean. So, when i write if (obj == null) in C#, not many would think it will be converted to something like if (!obj) in javascript, as it is unexpected. I would understand if you converted that to if (obj === null), even though it would break my existing code when obj is undefined, but if (!obj) doesn't seem logical at all.

Consider the case below, in javascript:

var obj = 0; // C# object obj = 0;

if (obj === null) alert('object has null value?'); // C# if (Script.IsNull(obj))...
if (!obj) alert('object has null value!?'); // C# if (obj == null) ...

My recommendation for Script.IsFalse would be like this:

if (Script.IsFalse(obj)) ==> if (!obj)
if (Script.IsTrue(obj)) ==> if (!!obj)

Btw, in javascript (null == undefined) -> true and (null == 0) -> false, so obj == null is equal to obj === null || obj === undefined. So  its a shorthand way to  Script.IsNullOrUndefined. I didn't see any script where people write such verbose code to check for null or undefined values.

**Comment by nikhilk** [comment]
Fix included in 0.7.2.0 release.
