### ISSUE TITLE
.pdb's and .NET Framework 2.0

### ISSUE THREAD

**Issue by Mike-E-angelo** [nikhilk/scriptsharp#310]
Hello again. :)

I've been digging through the core assemblies and noticed that the .pdb's aren't created in debug mode, and that the target framework is 2.0.  I was curious about the thinking behind that.

Also, I just wanted to verify the use/intention of this "Issues" section... if there is a forum or better location for these types of questions, please let me know.  I hate the thought of unnecessarily cluttering this space with the wrong sorts of activity.

Thank you!

**Comment by nikhilk** [comment]
This is fine use of the issues list. Ideally github would have a forum section, but it doesn't. Pure how-to questions probably make sense on stackoverflow.

The pdb doesn't make sense, as the assembly is never used at runtime... hence by default turned off in the scriptsharp.targets file.

Framework version fixed to 2.0 since newer versions caused some issues in the c# compiler ... but it too doesn't matter, as the generated assembly is not executed.

**Comment by Mike-E-angelo** [comment]
Great... thanks for the clarification Nikhil!
