### ISSUE TITLE
What are the expectations for import scripts on large JS libraries?

### ISSUE THREAD

**Issue by theoutlander** [nikhilk/scriptsharp#332]
I've been using a few JS libraries that have massive API's like Google Maps, ElasticSearch, and a few others that aren't as huge but fit the problem that I'm about to describe.

While I'd like to port those over to S#, it is not possible to reach 100% coverage in a short timeframe. At the same time, generally we don't need more than a handful of API's to get started with the libraries for basic scenarios.

I'd like to address that problem by staying lean and porting the API to S# as I'm consuming it in my project and incrementally building upon it as I use additional functionality. It will also allow other users to take advantage of the functionality that is exposed and start to contribute back to those API's as their needs grow.

My goal is to get to 100%, but I don't want to wait a very long time before being able to release anything.

What are your thoughts on this?

**Comment by nikhilk** [comment]
Real good question. I don't know the right answer, but will share my opinions/thoughts. It would be great for folks to chime in, as well as share any suggestions on increasing coverage - how, what would be valuable to see covered that sort of thing.

In general, there is obviously value to having "full" (for some pragmatic definition of full) coverage of a library. However this is quite time consuming and often an endeavor in itself (from experience doing the jQuery and Bing maps ones). They also need to be kept up-to-date or even full mappings become partial.

My opinion has probably shifted a bit to value partial imports more over time. For example, the HTML one is by no means complete given all the new HTML5 APIs that have emerged. I just did the Node one and few related modules, and they're still incomplete.

I think there is an interesting and line between what is ready to be shared vs. what should just remain private. If reasonable scenarios can be accomplished with the import assembly, then great, lets share it. Also, it would be nice whenever possible to complete a class, rather than leave it full of holes, so that it doesn't create confusion when someone picks up an import library and continually runs into missing stuff.

The other dimension to think about how to scale this is model for sharing and collaboration on two dimensions... the OSS collaboration aspect, and technical aspect.

Originally I envisioned a core set of libraries would be an integral part of the script# project. Stuff that well over 80% of script# users use, and have them rev alongside the compiler, so you're guaranteed these exist and work with every new compiler version... and then a complementary ecosystem of projects for the breadth of things out there. Completeness on the former set would be more desirable. These could be run by different folks (who know and use the API they are importing) and hopefully they keep up with the main project, publish in similar manner on nuget, so they're consistently searchable, but they may progress at different stages. I could create a "ScriptSharp" team here on github to provide an unifying umbrella, so they're easy to find and correlate.

On the technical front, it would be interesting to leverage some of the ecosystem around building TypeScript type declarations and use them as a starting point for mapping into c# APIs. If done right, I think the biggest value I see from TypeScript is actually a standardized format for documenting script APIs. I haven't looked too deeply into using them as the basis of generating import assemblies, as I've found writing good import assemblies is often a manual task requiring some level of judgement on structuring the APIs, and hard to fully automate, but maybe good enough for a starting point.

OK, those were a bunch of thoughts on the topic. I am relatively sure we need to do the multiple projects thing to scale out. It would be great to hear what others have to say on the topic.

**Comment by dlev-** [comment]
I just posted this gist https://gist.github.com/dlev-/5902234 that does a number of find/replaces to roughly convert a typescript definition to a script# import wrapper. It's not perfect, and it doesn't do everything, but I find it gets you about 80% of the way there.

**Comment by michaelcheers** [comment]
@dlev-, @nikhilk, I have a program that should give much better results (hopefully). It's called [TypescriptToCS2](https://github.com/michaelcheers/TypescriptToCS2). Though, it currently only works with  [Bridge](https://github.com/bridgedotnet/Bridge), I would love to expand it to Script#.
