### ISSUE TITLE
Cannot convert anonymous method to type 'System.Delegate' because it is not a delegate type

### ISSUE THREAD

**Issue by LucasOromi** [nikhilk/scriptsharp#338]
Hi,

I am trying to write something like:

var ApplicationModule = angular.module("Application", function() {
})

the module method is defiled like this:

AngularModule module(string name, Delegate configFn);

I have tried several ways. The first I was using lambda expressions and was not accepted. But then I am not allowed to write it this way either:

[Mixin("")]
    public class Module
    {
        public static AngularModule ApplicationModule;

```
    static Module()
    {
        ApplicationModule = AngularGlobal.angular.module("Application", delegate()
            {
            });
    }
}
```

I get this error:

Error   3   Cannot convert anonymous method to type 'System.Delegate' because it is not a delegate type

**Comment by nikhilk** [comment]
I don't think anonymous delegates can be defined like that, because the c# compiler doesn't know what type of delegate to create. I believe the error you are seeing is coming from the c# compiler, and this doesn't even get to the script# compiler.

Define the signature of the module method as follows:

```
AngularModule module(string name, Action configFn)
```

That will tell the c# compiler what signature to expect for the delegate, and then your anonymous method will match the expected signature.
