### ISSUE TITLE
Error in mscorlib.js

### ISSUE THREAD

**Issue by mhanna** [nikhilk/scriptsharp#366]
Hi,

Following the direction of Perpetuum Software Support, i'm writing the problems i had encountered using the mscorlib.js.

The problem as far as I can see is that library defines Global prototypes of base Javascript functionality (For instance, Array object) and that is in conflict with other libraries.

My problems occurs since i use another third party which in turn invokes, not intentionally, these prototypes. 

Regards,

Mhanna Abu-Tareef

**Comment by nikhilk** [comment]
I don't know which specific version of script# Perpetuum uses for its product, but the current version (in the repository), 0.8, has a fairly different script runtime.

One of the explicit goals of the new runtime was to have zero impact on the script environment ... so no globals, as well as no extensions on any built-in script types or prototypes.

Given you seem to be using Perpetuum rather than script# directly, you'd need to have them create a newer version of their product that relies on an updated script# version. Makes sense?
