### ISSUE TITLE
jQuery application project template might be incorrect

### ISSUE THREAD

**Issue by theoutlander** [nikhilk/scriptsharp#388]
Not sure if this is intentional or not, but when I create a jQuery Application I don't get an AMD module. 

I was expecting being able to use the generated file in an AMD pattern. However, the template is missing the define('{name}',....) and return $exports statement. 

If you agree, I can patch it and send a pull request. Thanks!

**Comment by nikhilk** [comment]
The jQuery App template doesn't create an AMD module since I guess I was trying to distinguish between app and module/plugin where the latter is a reusable module and the former isn't. Consequently the app template only declares dependencies, whereas the plugin project template declares itself, in addition to specifying dependencies.

The same is true for HTML App vs. HTML module projects.

Do you buy that distinction?

**Comment by theoutlander** [comment]
Ok that makes sense. I was confused between jQuery Application and Plugin.
