### ISSUE TITLE
Use classes from HTML

### ISSUE THREAD

**Issue by athalay** [nikhilk/scriptsharp#411]
Dear All,

So far we have been using SS 0.7.5, now we are about creating a new project with 'cc'/0.8.

The first problem we face is:
1. We create an SS project (installed 0.8 template) and compile it
2. In the HTML we have the following 'includes:

```
<body>
        <script type="text/script" data-name="ss" data-src="/Scripts/ss.js" data-autoload="true"></script>
        <script type="text/script" data-name="Application1" data-src="/Scripts/Application1.js" data-autoload="true"></script>
        <script src="/Scripts/ssloader.js"></script>
        <script type="text/javascript">
            require(['Application1'], function (Application1) {
                var z = Application1.Class1();
                z.hi();
                alert('bela');
            });
        </script> 
[...]
```

I wouldn't put this into the BODY, however the samples follow this pattern.

My 'alert' is never called, nor my Class1 is ever created :(

Originally I want to use code in my document.ready callback, of course, this doesn't work also:

```
<script type="text/javascript">
        $(document).ready(function(){
            var z = Application1.Class1();
                        z.hi();
        });
    </script>
```

Any fast help would be really appreciated, cause we consider SharpKit also (which works), however in the past we've been using SS.

**Comment by theoutlander** [comment]
Have you checked the tutorials here: https://github.com/nikhilk/scriptsharp/wiki?

Hello world specifically: https://github.com/nikhilk/scriptsharp/wiki/Creating-your-first-HTML5-Application:-Hello-World

Once you're past hello world: https://github.com/nikhilk/scriptsharp/wiki/Building-a-spreadsheet-in-Script%23-using-HTML5

**Comment by athalay** [comment]
Dear theoutlander,

I did, and none of what you enlisted mentioned anything I want. I want to call my custom SS-classes (of course which generated into the .js file) from HTML. Example, when an HTML page loads, then I want to call (SS 0.7.5 syntax) Scripts.UserManager.initialize().

Where "Scripts" is the ScriptNamespace (in 0.7.5), and "UserManager" is my public class, and "Initialize" is a static method on it.

All example available contains only the static Page class which fires up the logic, which is not good for me, I want to call specific methods on my custom classes.

Or did I miss anything somewhere?

**Comment by theoutlander** [comment]
Sorry, I'm a bit confused with what's going on. I don't have access to a computer right now, but can you check the chrome debugger to see if there are any console errors? What happens if you try to put a breakpoint and step through?

Sent from my Windows Phone

**Comment by theoutlander** [comment]
Can you post your solution somewhere as a zip and I can try it out. Just to make sure, is your class defined as a module?

**Comment by athalay** [comment]
Dear theoutlander,

https://www.dropbox.com/s/ywu1s1z65f8jrij/Application1.zip

Be aware that if you recompile the SS project, you have to copy the .js to the MVC-webprojects' Script folder (I know you know this, just to be sure).

No, my class is not a module, therefore it isn't a static class, I want to instantiate (please check Layout.cshtml) and call its methods. Isn't it possible to access/use non-static classes from HTML?

The require/jss_loader part ('includes') might be messy, because to be sure, I have zero clue (based on the examples also) how to use them :(

**Comment by theoutlander** [comment]
Sorry, I don't have a lot of time to fix this and send it back. I took a look and the problem is with the template. You should replace Application1\Properties\AssemblyInfo.cs with something like (to create a module which returns the classes within it):

```
// A script template providing an AMD pattern-based structure around
// the generated script.
[assembly: ScriptTemplate(@"
/*! {name}.js {version}
 * {description}
 */

//""use strict"";

define('{name}', [{requires}], function({dependencies}) {
  var $global = this;

  {script}
  return $exports;
});
")]
```

Your output file will look something like this:

```
/*! Application1.js 1.0.0.0
 * 
 */

"use strict";

define('Application1', ['ss'], function (ss) {
  var $global = this;

  // Application1.Class1

  function Class1() {
  }
  var Class1$ = {
    hi: function() {
      alert('Hi!');
    }
  };

  var $exports = ss.module('Application1', null,
    {
      Class1: [ Class1, Class1$, null ]
    });

    return $exports;
});
```

Also you want to make sure that you do instantiate the class like this:

```
require(['Application1'], function (Application1) {
        var obj = new Application1.Class1();
        obj.hi();
});
```

Hope that helps.

**Comment by athalay** [comment]
Dear theoutlander,

Thanks a lot, now the require-callback is executed (yes, I missed out the 'new', was a stupid rookie mistake).

I have 2 additional questions:

Which of the 'includes' are required from the list below?

```
<script src="/Scripts/require.min.js"></script>
<script type="text/script" data-name="ss" data-src="/Scripts/ss.js" data-autoload="true"></script>
<script type="text/script" data-name="Application1" data-src="/Scripts/Application1.js" data-autoload="true"></script>
<script src="/Scripts/ssloader.js"></script>
```

Also, is there any way, to use my classes at document.ready (wired up by jQuery)?

Because if I have this

```
<script type="text/javascript">
        $(document).ready(function () {
            // I want to use my Class1 here
            var z = new Application1.Class1();
            z.hi();
        });
    </script>
```

, then I still get undefined error.

**Comment by athalay** [comment]
Sorry to push this further, but I can't make the following work either:

```
$('#alma').click(function () {
            var z = new Application1.Class1();
            z.hi();
        });
```

I understand that I could (should?) wire these up in SS, but in some cases this might not be possible/necessary, and I just wanna access my classes.

**Comment by nikhilk** [comment]
I think its important to understand the core pattern here - that classes etc. are not pushed to the global context anymore, like good/modern scripting patterns suggest. The idea is in the new world, you include a script module loader (ssloader.js is one, require.js is the generally used one), and then introduce code within define (when defining a module) or within require (when not introducing a module), and in either case, specify the list of dependencies for the loader to ensure they've been loaded, and to pass them in into the function containing your code.

Something like this would be my guess:

```
<script src="/Scripts/require.min.js"></script>
<script>
  require(['jQuery', 'ss', 'Application1'], function ($, ss, Application1) {
    var obj = new Application1.Class1();
    obj.hi();

    $('#alma').click(function () {
        var z = new Application1.Class1();
        z.hi();
    });
  });
</script>
```

Of course, you could also just write all of this code in script# (see the Page template). In particular you'll see a different script template in AssemblyInfo in that template - one that creates a script requiring dependencies, rather than the regular Script library template, which has a define.

Hopefully this helps explain the concepts at play, which then help you work through your specific scenarios.

**Comment by athalay** [comment]
Dear nikhilk and theoulander,

Thanks for the reply, however we still couldn't make this work.

I have the following code in HTML:

```
<script src="/Scripts/require.min.js"></script>
        <script type="text/script" data-name="jquery" data-src="/Scripts/jquery-1.8.2.min.js" data-autoload="true"></script>
        <script type="text/script" data-name="ss" data-src="/Scripts/ss.js" data-autoload="true"></script>
        <script type="text/script" data-name="Application1" data-src="/Scripts/Application1.js" data-autoload="true"></script>
        <script src="/Scripts/ssloader.js"></script>
        <script type="text/javascript">
            require(['jquery', 'ss', 'Application1'], function ($, ss, Application1) {
                alert('I want to break freeee!');

                $('#alma').click(function () {
                    var z = new Application1.Class1();
                    z.hi();
                });
            });
        </script> 
```

If 'jquery' is not in the require-list, then the callback (including the alert) gets called -> awesome!

If jquery is in the require-list (like in the snippet above), the callback is not called at all! DO we have to use a special jquery.js in here, or?

Please notice I also included both require.min.js AND ssloader.js. If I leave ssloader out (and require.min is still included), then the require-callback is called, however all arguments ($, ss, Application1) is null.

If I leave require.min out and ssloader in, the callback is not called either.

Thanks a lot for your effort helping us!

**Comment by kirakosyan** [comment]
HI, facing the same problem
I have jquery included before using Bundle
so this just does not work since trying to fing jquery.js which obviosly does not exist

Common.js
define('Common', ['ss', 'jquery'], function(ss, $) {

**Comment by theoutlander** [comment]
It's most likely not finding the path to jquery. What do you see in the chrome debugger? It should tell you the path where it's trying to look for jquery. In your project you should have jquery in that location. 

What I do in my projects usually is define a path for libraries to load latest from a CDN. However, I use RequireJS.

**Comment by kirakosyan** [comment]
Hi , thanks for the response

After removing jquery from bundle and adding data-name it started to work.
Now I am facing another similar problem, when added jqueryUI to S# project I am able to build and web does not show. I checked JS is loading, but I put a breakpoint after DEFINE and it never hits :(

My Common project looks like
   define('Common', ['ss', 'jquery', 'jqueryUI'], function(ss, $, jqueryUI) {

My web site starts with 

```
<script src="/Scripts/ssloader.js"></script>
<script type="text/script" data-name="ss" data-src="/Scripts/ss.js" data-autoload="true"></script>
<script type="text/script" data-name="jquery" data-src="//ajax.aspnetcdn.com/ajax/jQuery/jquery-2.1.0.min.js" data-autoload="true"></script>
<script type="text/script" data-name="jqueryUI" data-src="//ajax.aspnetcdn.com/ajax/jquery.ui/1.10.4/jquery-ui.min.js" data-autoload="true"></script>
<script type="text/script" data-name="Common" data-src="/Scripts/Common.js" data-autoload="true"></script>
```

**Comment by kirakosyan** [comment]
I can see the same issue with ToDoWeb project in samples I got from Github

I added jqueryui to scriptsharp project
and added link 

<script type="text/script" data-name="jqueryUI" data-src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js" data-requires="jquery"></script>

to web project. Then web just stoped to work. Page loads fine without errors but does not work as expected. after just removing jqueryui it starts to work

**Comment by theoutlander** [comment]
Can you post your project as s zip? I haven't used 0.7.x in a long time. You should upgrade to the latest development branch.

From what I can see, the problem might be related to not using the module loader to load the files. You need to do something like require(['Common'], function(common) {...});

**Comment by kirakosyan** [comment]
I have tested the issue on 0.8 sample from github, it is also failing
Here you can download a little bit modified project
http://www.barracudagames.com/todo.rar

I just added jQuery UI package from Nuget, then it stoped to work.

Here is the original solution
https://github.com/nikhilk/scriptsharp/tree/cc/samples/Todo

**Comment by theoutlander** [comment]
It seems to work fine for me. What issues are you facing (ie: what doesn't work as it's supposed to)? Which browser are you using? Did you run this under a web server?

**Comment by kirakosyan** [comment]
hi, 
Does not work means: when you enter something in textbox and press enter nothing happens, since scriptsharp is not loaded. If will remove jqueryUi from script# project it will work,
I have tried with different browsers and on web server.

I have also published for you on http://td.azurewebsites.net/ so you can test it online.

**Comment by theoutlander** [comment]
Thanks for hosting. I see what you mean - I can repro the problem, but I'm not sure what the issue is!

Here's a link to the compiled zip that you sent me: https://dl.dropboxusercontent.com/u/28584686/example/TodoWeb/Default.htm

The only modification I made is that they're pointing to the shared non-minified resources off dropbox instead of the relative (/scripts) path. If you load it in the browser, does it work for you?

Link to folder with only todoweb app: https://www.dropbox.com/sh/dud43ark1xcdtdf/ABXNKDNPQQ/example/TodoWeb

Perhaps you can diff all the html/js/css resources in the todoweb folder?

**Comment by kirakosyan** [comment]
hi
Your sample is working becouse you did not add jqueryUI nuget package to your S# project, so todo.js looke like this for you
define('Todo', ['ss', 'jquery', 'jqueryTmpl'], function(ss, $, jqueryTmpl) {

and mine 
define('Todo', ['ss', 'jquery', 'jqueryTmpl', 'jqueryUI'], function(ss, $, jqueryTmpl, jqueryUI) {

jqueryUI breaks execution. That is the problem, for it sounds like a bug

**Comment by theoutlander** [comment]
Oops missed that. I built the project you had sent me so there might be something else wrong in there?

Sent from my Windows Phone

**Comment by kirakosyan** [comment]
Not sure what can be wrong, just ensure that there is a reference to Script.jQuery.UI in S# project.
Who can confirm if it is a bug ?

**Comment by theoutlander** [comment]
I see that the project you shared didn't have that reference. I tried adding the reference and I can repro the behavior. Let me see if I can figure out what's wrong.

**Comment by theoutlander** [comment]
It might be a compatibility issue between jquery and jquery UI. 
I even tried jquery ui 1.8.1, but still saw the same problem. No exceptions were thrown anywhere.

Next I would try with require JS and if that fails, then look into creating a project from scratch with just jquery and jquery ui to see if you can repro the problem. 

Maybe @nikhilk might know what's going on here.

**Comment by kirakosyan** [comment]
I tried from the scratch, the same problem. with VS2012 and VS2013, no luck.
tried to debug , debugger never goes after require line.

**Comment by theoutlander** [comment]
Did you try requireJS ?

**Comment by kirakosyan** [comment]
it did not help

**Comment by nikhilk** [comment]
jQueryUI is a set of plugins that extend jquery ... IIRC, when you load with requirejs, you need to define a shim as part of requirejs config for jquery plugins. There are docs on requirejs explaining that.

The absence of a module being defined causes that dependency to never get resolved, causing your method to not get called. I didn't debug/run your code, but I am like 99% sure that is the case.

The script# loader is strictly an AMD loader - it doesn't care for (or support) loading scripts that aren't AMD-compatible. If you see the sources of the script# loader, you'll see a TODO for supporting those sort of scripts, but honestly I don't really feel inclined. Constraining to just supporting AMD scripts (and furthermore explicitly named modules, rather than anonymous modules, while we're talking about limitations... also doc'd in the code) makes the script# loader extremely light-weight (relatively speaking).

Hope that helps.
