### ISSUE TITLE
Populate dropdown box / combo box dynamically using Script#

### ISSUE THREAD

**Issue by parthangshu** [nikhilk/scriptsharp#416]
Hi,

I have create one dropdown box and in that dropdown I need to populate data from database using loop. For instance I have populate all Students roll numbers in that dropdown.

Please help!!!
Thanks in advance.

Regards,
Partha

**Comment by nikhilk** [comment]
I'd recommend asking these "how to" questions on stackoverflow - use the scriptsharp tag (see: http://stackoverflow.com/questions/tagged/script%23). This is better for issues... though I do wish github also had a forum feature for this style of Q&A.

Also, as suggested in your previous two questions, did you have a sense of what javascript you need for your scenario, and writing the c# code based on that, rather than assume there is some special script# way of doing things?
