### ISSUE TITLE
ScriptSharp.Runtime fails to build when referencing an import project

### ISSUE THREAD

**Issue by theoutlander** [nikhilk/scriptsharp#421]
I'm on the latest CC branch. I have a project that is imports only that I'm referencing in another project called Core.

Core is referenced by a web application. The web application also has ScriptSharp.Runtime package referenced.

When I build core, I get the following error: 

**.....packages\ScriptSharp.Runtime.0.8\tools\ScriptSharpWeb.targets(14,5): error : Unable to find scripts list for project IDM.Common.Client.ScriptImports.**

This occurs only when the web project references the ScriptSharp.Runtime package. If I remove that reference, everything builds.

Under the hood, it appears that the builder is looking for a generated JS file. If I change the project file to generate an empty JS script, everything works fine. 

Is there something I need to do differently? Is this a bug?

**Comment by nikhilk** [comment]
The deployment task that copies scripts from dependencies looks for projects with a ScriptSharp property set to true. This is set to true by ScriptSharp.targets, but that shouldn't be imported into Import library projects...

The thing to check for is if your imports only project is including the ScriptSharp.targets msbuild file. I wouldn't expect it to since there is no javascript to generate from that.

**Comment by theoutlander** [comment]
I think I ran into this problem because I upgraded my application to use the latest build. The build it was referencing was from over a year ago. I had to uninstall S#, all the referenced S# packages and then recreate that import project that was complaining and everything works fine. 

There's a good chance that I missed something. I think scriptsharp was set to true in the project file and that could have been the problem. I thought it should have been true since it was a s# project, but it makes sense why it should have been false.
