### ISSUE TITLE
DateTime

### ISSUE THREAD

**Issue by rotem-hen** [nikhilk/scriptsharp#441]
I know System.DateTime class was removed.
What can I do about my huge project using it?
Will just changing everything to "Date" solve it? Can I get the DateTime class and add it manually?

Thanks,
Rotem.

**Comment by scottdurow** [comment]
In all honesty I've not seen the benefit of the changes made after v0.7.6  - I still use this release which is very stable.

**Comment by rotem-hen** [comment]
I see. It's just that I work in a big company and need to find a solution for this. I would like to find something that will allow us to advance to the newer versions. Any ideas?

**Comment by scottdurow** [comment]
You have to ask yourself why you need to advance to the newer version. Nikhil isn't developing this any further. If you need an active project, you should check out Bridge 2.0 which will be released soon - this looks like it will be more compatible with Script# 0.7.6 since it is merging with http://saltarelle-compiler.com/

**Comment by rotem-hen** [comment]
OK, thank you so much for your help!
