### ISSUE TITLE
jQueryEvent.Which

### ISSUE THREAD

**Issue by lucidvizion** [nikhilk/scriptsharp#46]
Return type on this property is actually an int in jquery - it is string in script#

**Comment by Lightw3ight** [comment]
I noticed this too, I also noticed a whole lot of properties were missing from the jQueryEvent object such as altKey, shiftKey etc: http://api.jquery.com/category/events/event-object/

**Comment by keremkusmezer** [comment]
It think they need to the fixed also, i developed extended mappings to access this properties for my project.

**Comment by nikhilk** [comment]
Its great to see the bug, but it would be even better to see some help here beyond reporting bug fixes esp. if you already know what is missing, what needs to be added/removed/changed, or even have the work done for your project. Can you put it in the bug along with the doc-comments, or show what it needs to be a in a gist or a fork. That is the whole point of putting this on github ... otherwise, I would just keep releasing binaries.

Anything done in that direction will only help get it out faster.

**Comment by robitar** [comment]
I think there might be an adjustment period while people get used to idea of contributing to Script#, I've been using it since it was first announced all those years ago, but it's only now that there's a central place where people can contribute mappings/bugfixes etc.

Because the bindings are here, a pull request with the edits would be ideal, if you were willing to accept them. Failing that, I think I would just clone the repo and send you links to my commits.

**Comment by nikhilk** [comment]
Yes, I agree - this is all new, and still in the forming stages.

I am fine with any approach - specific things in the issue item, a gist, a link to commit or pull request. Whatever works for people.

**Comment by nikhilk** [comment]
Fix included in 0.7.2.0 release.
