### ISSUE TITLE
ExtJs 4 derived class problem

### ISSUE THREAD

**Issue by accacc** [nikhilk/scriptsharp#61]
Hi,

i am playing http://extsharp.codeplex.com/ source code,but i am facing a problem,the problem is if i extend a class,i given below error.

Error: too much recursion
Source File: http://localhost/Scripts/mscorlib.debug.js
Line: 1170

example:
 public partial class SubmitButton : Button
  {  
  }

**Comment by robitar** [comment]
You cant derive a class from Button, because its just an imported wrapper around native ExtJS functionality, its not a real class.

http://extsharp.codeplex.com/SourceControl/changeset/view/67228#1716533

If you have a quick look at the above link, you'll see the [Imported()] attribute, which means that the type is just an empty wrapper over some native script.

I'm not familiar with how the type system works in ExtJS, but you will probably have a hard time shoehorning a ScriptSharp class into it. You might try using static methods to act as member functions you want, and then wire them all up at runtime in native script.

**Comment by nikhilk** [comment]
Right - you're likely going to be able to import existing ExtJs classes to make things work, but the class pattern in each framework is unique, and unlikely that you can derive from an ext class ... at least easily. You can use (I.e) compose ext classes within your script# classes, assuming you have the imported classes defined.
