### ISSUE TITLE
DateTime? does not compile while double? and Nullable<DateTime> does.

### ISSUE THREAD

**Issue by vgribok** [nikhilk/scriptsharp#81]
public DateTime? PropertyName /MethodName()
{
..
}
gives "error : Syntax error: 'Identifier' expected" (at least in the partial class). Replacing with Nullable<DateTime> fixed the problem. double? has no problem compiling in the same class.

Cheers,
Vlad.

**Comment by nikhilk** [comment]
Yes, for now please use Nullable<DateTime> - the type? syntax was only implemented for intrinsic types such as int, bool etc.

**Comment by nikhilk** [comment]
Duplicate of #67.

**Comment by michaelaird** [comment]
This tripped me up today with some code that was being generated in a T4 template. using reflection, the type was emitted as Decimal instead of decimal. this caused the compiler to fail with the same error.

i changed the generator to use Nullable<> but it was some head scratching until i found this issue.
