### ISSUE TITLE
Unable to resolve or open included file '%code%' 

### ISSUE THREAD

**Issue by aronmek** [nikhilk/scriptsharp#97]
When I try to compile any project which does not reference Script.Web does not compile and complains the error above, This happens even if I'm not using anything from the Script.Web assembly.

**Comment by barryschulz** [comment]
Are you trying to use Script.Literal with curly braces that do not pertain to the args?

**Comment by nikhilk** [comment]
Unable to reproduce this.
Did you create a project using one of the script# project templates?

**Comment by nikhilk** [comment]
The bug only happens when generating documentation is enabled.

**Comment by nikhilk** [comment]
Fix included in 0.7.4.0

**Comment by DVaughan** [comment]
For anyone else seeing this error message. Be sure that when using Script.Literal, that curly braces that are not a part of arguments are escaped using double {{, like so:

Script.Literal("if (window.console && windows.console.debug) {{ windows.console.debug({0}); }}", message);

**Comment by nikhilk** [comment]
This error message is same (basically code-gen failed) for different root causes. The string literal scenario here is completely different - the issue there was an unintended dependence on requiring a reference to Script.Web, and that was fixed.

Please file a new bug rather than overloading this one, so the compiler doesn't fail this way for a badly formatted string literal format string.

**Comment by DVaughan** [comment]
Done

**Comment by divyeshtopiya** [comment]
this issues also comes when using dictionary's remove method and key is defined as an enum type which is integer type say  Dictionary<days,object>();

public enum days
{
    sunday = 1,
    monday = 2,
    tuesday = 3
}
