### ISSUE TITLE
When a base method is called and that method calls another base method which is overridden then scriptsharp calls the derived method

### ISSUE THREAD

**Issue by aronmek** [nikhilk/scriptsharp#98]
When a method from a base class is called and that method calls another base method which is overridden in the derived class then scriptsharp calls the derived method instead of the base's method.

Here is an example

<pre>

    public class Foo {
        public virtual void Func1() {
            Script.Alert("Foo.Func1");
        }

        public virtual void Func2() {
            Script.Alert("Foo.Func2");
            this.Func1();
        }
    }

    public class Bar: Foo {

        public override void Func1() {
            Script.Alert("Bar.Func1");
        }

    }

[GlobalMethods]
public static class Global {
    [PreserveName]
    public static void Test() {
        Bar test = new Bar();
        test.Func2();
    }
}
</pre>

When I call the global Test function the expected flow is.

<pre>
    Foo.Func2()
        Foo.Func1()
</pre>

But instead it goes

<pre>
    Foo.Func2()
        Bar.Func1()
</pre>

**Comment by nikhilk** [comment]
This is exactly the expected behavior. Here is the equivalent console app running vanilla managed code:

```
using System;

public class Foo {
    public virtual void Func1() {
        Console.WriteLine("Foo.Func1");
    }

    public virtual void Func2() {
        Console.WriteLine("Foo.Func2");
        this.Func1();
    }
}

public class Bar: Foo {

    public override void Func1() {
        Console.WriteLine("Bar.Func1");
    }
}

public static class Global {
    public static void Main() {
        Bar test = new Bar();
        test.Func2();
    }
}
```

And the output:

```
Foo.Func2
Bar.Func1
```

**Comment by aronmek** [comment]
Oh you're right, But there is still something different I'll have to investigate it more deeply to see the ins and outs to demonstrate it properly.

**Comment by aronmek** [comment]
Ok here it is, I was intending to do hiding and not overriding and scriptsharp handles it as if i did overriding.
scriptscharp code.

<pre>
public class Foo {
        public void Func1() {
            Script.Alert("Foo.Func1");
        }

        public void Func2() {
            Script.Alert("Foo.Func2");
            this.Func1();
        }
    }

    public class Bar: Foo {

        public void Func1() {
            Script.Alert("Bar.Func1");
        }

    }
}

[GlobalMethods]
public static class Global {
    [PreserveName]
    public static void Test() {
        Bar test = new Bar();
        test.Func2();
    }
}

//outputs
//Foo.Func2
//Bar.Func1
</pre>

Managed code

<pre>
using System;

public class Foo
{
    public  void Func1()
    {
        Console.WriteLine("Foo.Func1");
    }

    public  void Func2()
    {
        Console.WriteLine("Foo.Func2");
        this.Func1();
    }
}

public class Bar : Foo
{

    public void Func1()
    {
        Console.WriteLine("Bar.Func1");
    }
}

public static class Global
{
    public static void Main()
    {
        Bar test = new Bar();
        test.Func2();
    }
}

// Outputs
// Foo.Func2
//Foo.Func1
</pre>

**Comment by nikhilk** [comment]
I would expect first that you'd get a warning from the c# compiler that you have to use the new keyword, since Func1 is same name as one that is being inherited. The moment you do that, I believe the script# compiler will complain that new isn't supported.

This isn't a compiler limitation. This is a script limitation. Script doesn't have the concept of "new" and hiding - if you add to the Bar.prototype it is going to override what is on Foo.prototype.

One way to get around that is to avoid prototype chaining and instead explicitly call members off the prototype itself. Eg. Foo.prototype.func1.call(fooInstance, [args]) instead of fooInstance.func1(args) ... this is both ugly, slower, and breaks the normal override scenario, since the member on Bar.prototype wouldn't get invoked if you directly access Foo.prototype.
